app_blog/urls.py
from django.urls import path
from .views import render_posts, post_detail
from django.urls.resolvers import URLPattern

app_name = 'blog'

urlpatterns = [
    path('',render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

app_portafolio/urls.py
from django.urls import path
from . import views
from django.urls.resolvers import URLPattern


urlpatterns = [
    path('', views.home, name='home'),
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from app_blog import views
from app_portafolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('app_blog.urls')),
    path('',include('app_portafolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/models.py
from django.db import models
import datetime
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='bolg/images')
    date = models.DateField(datetime.date.today)

    

app_portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField
# Create your models here.


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=100)
    image = ImageField(upload_to='app_portafolio/image/') 
    url = URLField(blank=True)

app_blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.


def render_posts(request):
    posts = Post.objects.all()
    return render(request,'posts.html',{'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post,pk=post_id)
    return render(request,'post_detail.html', {'post':post})

app_portafolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    projects = Project.objects.all()
    return render(request,'home.html',{'projects' : projects})

app_blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h3>
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" />
    <div class="my-4">
    <p>{{ post.description|safe }}</p>
    </div>
</div>

{% endblock %}

app_blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>Posts</h1>
{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" />
            </div>
            <div class="col-9">
                <h2>{{ post.title }}</h2>
                <p>{{ post.description|striptags|truncatechars:100 }}</p>
                <p>{{ post.date|date:'M d Y'|upper }}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
        
    </div>
</div>
{% endfor %}

{% endblock %}

<!-- safe sirve para ejecutar las etiquetas dentro del archivo description  --> 
<!-- striptags sirve para no ejecutar las etiquetas dentro del archivo description y quitarlas   --> 

app_portafolio/templates/home.html
{% extends 'layout.html' %} {% block content %} {% load static %}
<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'app_portafolio/profile.jpeg' %}" />
  </div>

  <div class="col-md-8 my-auto">
    <h1>I am <strong>Ronald Madariaga</strong></h1>
    <h3>I am a Python Fullstack Developer</h3>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit iure
      doloremque eum? Dolorem animi qui excepturi sapiente nam expedita eum
      neque voluptates aspernatur sequi atque porro, harum hic tempora
      explicabo? Maiores similique, voluptatem cumque quos impedit velit
      excepturi necessitatibus quasi exercitationem iure itaque rem ducimus quae
      vitae sapiente deserunt. Fuga, cum? Expedita ad ea porro laboriosam labore
      sapiente ipsa, illum dolore accusamus necessitatibus officia deleniti fuga
      quod, laborum rerum quia. Repudiandae, explicabo eos? Doloremque id dicta
      quasi cumque deserunt, eius saepe, beatae, magnam soluta velit dolores
      repellendus! Nihil natus facilis velit consequatur? Quod itaque quis ipsum
      deserunt! Quos, sed numquam.
    </p>
    <a
      href="{% static 'app_portafolio/cv.pdf' %}"
      class="btn btn-primary btn-lg rounded-0 my-3"
      target="_blank"
      >Download CV</a
    >
    <a
    href="admin"
    class="btn btn-primary btn-lg rounded-0 my-3"
    target="_blank"
    >Administrador</a
  >
  </div>
</header>

<div class="row my-4 text-center">
  <h3>My project</h3>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe, fuga.</p>

  {% for project in projects %}

  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img
        src="{{ project.image.url }}"
        alt="{{ project.title }}"
        class="card-img-top"
      />
      <div class="card-body">
        <h2>{{ project.title }}</h2>
        <p>{{project.description}}</p>

        {% if project.url %}
        <a
          href="{{ project.url}}"
          class="btn btn-light roundede-0 btn-sm"
          target="_blank"
          >{{ project.url }}</a
        >

        {% endif %}
      </div>
    </div>
  </div>

  {% endfor %} {% endblock %}
</div>

app_portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Portafolio</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'main.css'%}">
  </head>
  <body class = "text-light">
    {% include 'partials/navbar.html' %}


    <div class="container p-4">
      {% block content %} 
      {% endblock %}
    </div>
    

    <footer>Footer</footer>
  </body>
</html>

app_portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">RM</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a
            class="btn btn-primary btn-sm"
            href="{% static 'app_portafolio/cv.pdf' %}"
            target="_blank"
            >Download CV</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>